### ISSUE TITLE
Encrypt then decrypt node issue with more than 16 chars message

### ISSUE THREAD

**Issue by AquiGorka** [pubkey/eth-crypto#47]
## Case
Bug

## Issue
Encrypt -> Decrypt is not working with `node@v12.2.0` with phrases more than 16 chars in length

## Info
  - Environment: node (originally found with node + browser, but could repro in node only too)

## Code

```JavaScript
  const publicKey =
     '030dddc2e1cb1f9c5c3463399f0b539e2f2a9d42678f596cef95ce301087c05836'
   const privateKey =
     '6b463fdd6b15df6da6753fe8d1a5973b133c7a4aed77b38b145b11987cf27876'
   let randomStr
   let answer
   let challenge
   try {
     randomStr = crypto.randomBytes(6).toString('hex')
     //randomStr = '1234567889012345'
     console.log('randomStr: ', randomStr)
     challenge = await encryptWithPublicKey(publicKey, Buffer.from(randomStr))
     console.log('challenge: ', challenge)                                                                                                                        
     answer = await decryptWithPrivateKey(privateKey, challenge)
   } catch (e) {
     console.log('Error: ', JSON.stringify(e, null, 2))
   }
 
  console.log('----> ', randomStr === answer)
```

Error thrown (only `node@12.2.0`):

```JavaScript
Error:  {
  "library": "digital envelope routines", 
  "function": "EVP_DecryptFinal_ex",
  "reason": "bad decrypt",
  "code": "ERR_OSSL_EVP_BAD_DECRYPT"
}
---->  false
```

`Node@11.4.0` gives a satisfactory: `---->  true`

**Comment by HP213** [comment]
Yes it is not decrypting message with more than 16 characters

**Comment by pubkey** [comment]
I added a test in the attached commit.
I think this has something to do with the openssl version. Can you run `openssl version` and post the output?

**Comment by pubkey** [comment]
https://travis-ci.org/pubkey/eth-crypto/builds/567377666

Some things I noticed:
`npm install` fails because of `ecdh.target.mk:113: recipe for target 'Release/obj.target/ecdh/ecdh.o' failed` see [here](https://github.com/cryptocoinjs/secp256k1-node/issues/89)

Then because of the failed build there is a `MODULE_NOT_FOUND` with `Reverting to browser version` On the browser-version there is a different kind of padding of the public key which results in the error `EVP_DecryptFinal_ex`.

The current workaround is to downgrade to node v11.
I think this must be solved by [eccrypto](https://www.npmjs.com/package/eccrypto)

**Comment by pubkey** [comment]
I opened https://github.com/bitchan/eccrypto/issues/42

**Comment by pubkey** [comment]
Fixed by 45e7029de1d557f85a8ee3af88bc63c9ea884c2c.
I released [1.5.0](https://github.com/pubkey/eth-crypto/releases/tag/1.5.0).
Please update.

**Comment by AquiGorka** [comment]
Awesome @pubkey 🎉 🎉 
Thank you

**Comment by GeekRishabh** [comment]
@pubkey Still getting the same issue tried `1.5.1` as well .

**Comment by GeekRishabh** [comment]
This is only working if we have the debugger enabled in React Native.

Node : - 10.15.3
"react": "16.9.0",
 "react-native": "0.61.2",
 "eth-crypto": "1.5.1",

Sample Code 
```js 
const data =
  "https://test.com/alpha/sudotest?txnid=FR001&txnref=FR001&amt=1234567&cc=USD"; // message
const encrypted = EthCrypto.encryptWithPublicKey(
"be11a49bbc3ea85d2fc8cf097bfef8e2d48ed363ccfafa4de04adbe47527df374f651b437425bb9d453eef040fcbddce3363d990d15181e2e1cce694f4dc32e6", // publicKey
  data // message
);
encrypted
  .then(data1 => {
    const str = EthCrypto.cipher.stringify(data1);
    console.log(str);
  })
  .catch(e => {
    console.log("error", e);
  });
```

Decrypt Code
```js
const encryptedObject = EthCrypto.cipher.parse(
  "10b2dac2cc0fed11187eadf33bc4936c0292a2ea5a8384647fb26191311e2c455b539a289097b97b5b6a1a25a5c3880cb61b97e613c8d6d5959e91326a63fef17a47ec4540f08c204da77666290cba4a71a6518e5bc33a7cc381f11a9cdd851f45f957850ef1c61f766ace51f4b1b6063250cac109490ba1282d6fe2eda93c1e774a8a0ce9913e3d654628433a124c28093110059bae66ae6a65c62316ad47072b3b7b74006e50941a761b381731646fe7ea4c93f224a73b7da3c2eb3127b6b303"
);


const message = EthCrypto.decryptWithPrivateKey(
  "0x6cd8176f53335af2726d30ef9b2624e40425f099aca9fcf8995cceb410a030fb", // privateKey
  encryptedObject
);
message
  .then(data => {
    console.log(data);
    const Obj = queryString.parse(data, {
      arrayFormat: "index"
    });
    console.log(Obj, "Obj");
  })
  .catch(e => {
    console.log("error", e);
  });
```

I am only getting  `4567&cc=USD` from data after decryption in production while in debug mode  i am able to get complete data.
@pubkey @AquiGorka @HP213  Any clue?

**Comment by pubkey** [comment]
@GeekRishabh I have no clue and I think this should be another issue.
Maybe you can check with the debugger which module-path is taken [here](https://github.com/bitchan/eccrypto/blob/07fb766b1f47dcaf7832a59bebcdddc13a135bd7/index.js#L24) and then we can isolate the problem. This is likely something with `secp256k1` in react native.

**Comment by vuhuykhoi** [comment]
I still have this error at Version 1.5.2
@pubkey  can you check it again?

**Comment by pubkey** [comment]
@vuhuykhoi I cannot reproduce this and have spend too much time on it.
If you have this error, please debug into it and check whats is wrong.

**Comment by recepaltas** [comment]
Same Here. Can you help me for this. The decrypt text is showing debug console of Chrome but not showing the app. 
Error :unable to decrypt data

Any Solution ?

**Comment by GeekRishabh** [comment]
Hello @recepaltas You can check  my repo [here](https://github.com/geekrishabh/eth-crypto/)

**Comment by pubkey** [comment]
Can you make a PR?

**Comment by GeekRishabh** [comment]
Hello @pubkey My repo code has few old dependencies and also I will need to fix the test cases.
